# Sobre el curso {.unnumbered}

## Introducción a R y Rstudio (4 horas)

*Objetivo: que el estudiantado sea familiarice con la interfase de trabajo y la programación por objetos, del mismo modo que sean capaces de realizar tareas básicas tales como crear un script, un proyecto, objetos, ambientes e instalar paqueterías*.

## Importación de información y primera revisión de fuentes demográficas (4 horas)

a.  Importación de información a R en diferentes formatos

b.  Revisión de encuestas y ejemplos de importación de datos en formatos diferentes

c.  Revisión preliminar y limpieza de información

*Objetivo: que el estudiantado sea capaz de importar información desde diferentes formatos (.txt, .csv, .xlsx, .dta, .dbf) a R, así como de exportar sus resultados en estos formatos. Del mismo modo que sean capaces de revisar de manera preliminar los objetos de tipo `data.frame`: funciones `dplyr::glimpse()`, `skimr::skim()`, manejo de etiquetas y hacer subconjuntos de información*

## Revisión de elementos estadísticos básicos desde “tidyverse” (8 horas)

a.  Tabulados con `janitor::tabyl()` y uso de factores de expansión con `pollster::topline()`, `pollstter::crosstab`. Lectura e interpretación de tablas de doble entrada

b.  Estadística descriptiva básica (medidas de tendencia central, dispersión y de posición) con el paquete `{dplyr}`

c.  Gráficos univariados y bivariados usando `{ggplot2}` y extensiones de `{ggplot2}`

d.  Fusionado de información

*Objetivo: que el estudiantado sea capaz de realizar análisis estadísticos básicos utilizando encuenstas mexicanas*

## Estimaciones por intervalo y diseño complejo muestral (4 horas)

a.  Estimaciones para medias

b.  Estimaciones para proporciones

c.  Estimaciones para totales

d.  Estimaciones lineales de coeficientes

*Objetivo: que el estudiantado sea capaz de realizar intervalos de confianza, calculo de errores estándar con diseño muestral complejo y sepa evaluar la confiabilidad de sus estimaciones*


# Facilitadora {.unnumbered}

## Ana Ruth Escoto Castillo
Profesora de tiempo completo en la Facultad de Ciencias Políticas y Sociales, UNAM. Doctora en Estudios de Población por El Colegio de México, cuenta con el nivel I en el Sistema Nacional de Investigadores. Coorganizadora del capítulo de la CDMX de la iniciativa global Rladies. Le interesa el bienestar de la población, en el presente, analizando los procesos de desigualdad y exclusión en los mercados laborales latinoamericanos; y, en el futuro, a través del estudio de la sustentabilidad. Su experiencia en el ámbito académico se ha concentrado en el estudio de este bienestar, específicamente en el análisis sociodemográfico de las condiciones laborales y la vinculación del comercio exterior con el mercado de trabajo, en la relación del cambio climático y la distribución de ingresos, el consumo energético de los hogares y sus implicaciones ambientales. Posee experiencia en recolección de información estadística, diseño y control de procesos de recolección y su procesamiento. Ha aplicado diversos métodos y herramientas multivariadas, homologación de información y comparabilidad de fuentes en sus investigaciones, así como usa de diversos softwares estadísticos, y ha impartido clases de estadítica aplicada a nivel de licenciatura y posgrado. 